version: '3.9'

services:
  app:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - SECRET_KEY=django-u1@cxb&8k5u8gl5m9zgsv
      - ALLOWED_HOSTS=0.0.0.0,localhost
      - DEBUG=1
      - DB_NAME=db_stock
      - DB_USER=stc
      - DB_HOST=db
      - DB_PWD=timco.lk@Stc123
    depends_on:
      - db

  db:
    image: mysql:8.0.35
    restart: always
    environment:
      MYSQL_DATABASE: 'db_stock'
      MYSQL_USER: 'stc'
      MYSQL_PASSWORD: 'timco.lk@Stc123'
      MYSQL_ROOT_PASSWORD: 'timco.lk@Stc123'
    ports:
      - '3306:3306'
    expose:
      - '3306'