
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A000','WAYSIDE SALES','','','1','0','1');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A001','AMPARA DEPOT','','','0','1','1');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A002','PADIYATHALAWA DEPOT','','','0','2','1');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A003','BATTICALOA DEPOT','','','0','3','1');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A004','POTUVIL DEPOT','','','1','0','1');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A005','AGENCY DEPOT AKKARIPATTU II','','','1','0','1');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A006','AGENCY DEPOT NINDAVUR I','','','1','0','1');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A007','AGENCY DEPOT NINDAVUR II','','','1','0','1');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A008','AGENCY DEPOT KALMUNAI I','','','1','0','1');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A009','AGENCY DEPOT SAINDAMARADU','','','1','0','1');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A010','KATHANKUDY AGENCY DEPOT','','','1','0','1');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A011','AGENCY DEPOT SAMMANTHURA','','','1','0','1');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A021','ANURADAPURA DEPOT','','images/deport/A021.JPG','0','4','2');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A022','MEDAWACHCHIYA DEPOT','','images/deport/A022.JPG','0','5','2');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A023','TALAWA DEPOT','','images/deport/A023.JPG','0','6','2');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A024','PADAVIAY DEPOT','','','1','0','2');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A025','VAUNIYA DEPOT','','','0','7','2');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A026','MANNAR DEPOT','','','1','0','2');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A027','AGENCY DEPOT MANNAR','','','1','0','2');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A041','BORALANDA DEPOT','','','0','8','3');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A042','BADULLA AGENCY DEPOT','','','1','0','3');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A043','BANDRAWELA AGENCY DEPOT','','','1','0','3');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A044','ERABEDDA','','','1','0','3');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A046','HEEWELKANDURA DEPOT','','','1','0','3');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A047','UMAOYA DEPOT','','','0','9','3');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A061','KADAWATHA DEPOT','','','0','9','4');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A062','MIRIGAMA DEPOT','','','0','10','4');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A063','ORUGODAWATTA DEPOT','','','1','0','4');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A064','NAINAMADAMA DEPOT','','','0','7','6');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A065','WILLORAWATTE DEPOT','','','0','11','4');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A066','KALDEMULLA NEW DEPOT','','','0','12','4');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A067','EGODAUYANA DEPOT','','','0','13','4');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A068','MORATUMULLA DEPOT','','','0','14','4');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A069','MORATUMULLA - II DEPOT','','','1','0','4');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A070','PANNIPITIYA DEPOT','','','0','15','4');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A071','SUWARAPOLA AGENCY DEPOT','','','1','0','4');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A076','PILIYANDALA DEPOT','','images/deport/239.jpg','0','16','4');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A081','CHANKANAI DEPOT','','','1','0','5');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A082','NALLUR DEPOT','','','0','3','5');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A083','KANKASANTHURAI DEPOT','','','1','0','5');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A084','KOKUVIL DEPOT','','','1','0','5');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A085','VADUKKODAI DEPOT','','','1','0','5');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A086','VELVETTITHURAI DEPOT','','','1','0','5');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A087','JAFFNA DEPOT','','','0','4','5');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A088','CHAVAKCHCHERI DEPOT','','','1','0','5');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A089','ODDUSUDAN','','','0','2','5');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A101','KANKANIYAMULL DEPOT','','','0','1','6');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A102','KURUNEGALA DEPOT','','','0','2','6');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A103','NIKAWERATIYA DEPOT','','','0','3','6');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A104','MELSIRIPURA DEPOT','','images/deport/A104.JPG','0','4','6');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A105','PUTTLAM DEPOT','','','0','5','6');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A106','ANAMADUWA DEPOT','','','1','0','6');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A107','NARAMMALA DEPOT','','','1','0','6');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A108','MAKULPOTHA','','','1','0','6');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A109','BINGIRIYA','','','0','5','6');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A121','PALLEKELLE DEPOT','','','0','1','7');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A122','MATALE DEPOT','','','0','2','7');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A123','NELUNDENIYA DEPOT','','','0','3','7');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A124','ETHGALA DEPOT','','','0','4','7');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A125','DAMBULUOYA DEPOT','','','0','5','7');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A126','NAULA DEPOT','','','0','6','7');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A127','NAULA NEW DEPOT','','','0','7','7');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A141','RATMALANA DEPOT','','','0','17','4');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A142','KALDEMULLA DEPOT','','','0','0','8');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A161','BOOSA DEPOT','','','0','1','19');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A162','HAMBANTOTA DEPOT','','','0','1','9');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A163','MATARA DEPOT','','','1','0','9');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A164','UNAWATUNA DEPOT','','','0','2','9');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A165','AMBALANGODA DEPOT','','','0','3','9');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A166','BELIATTA DEPOT','','','1','0','9');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A167','KAHADUWA','','','1','0','9');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A168','WELIGAMA','','','1','0','9');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A169','TALALLA DEPOT','','','0','4','9');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A181','BUTTALA DEPOT','','','1','0','10');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A182','WELLAWAYA','','','0','2','10');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A201','NUWARA ELIYA DEPOT','','','0','1','11');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A202','KEPPITIPOLA DEPOT','','','0','1','20');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A203','KITULGALA DEPOT','','','0','2','11');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A204','HARASBEDDA DEPOT','','','0','3','11');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A221','MANAPITIYA / KADURUWELLA DEPOT','','','0','1','12');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A222','SANDUNPURA DEPOT','','','1','0','12');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A223','TRINCO DEPOT','','','1','0','12');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A224','CHINA BAY DEPOT','','','0','2','12');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A225','MINNERIYA DEPOT','','','0','3','12');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A226','HABARANA DEPOT','','','0','0','12');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A241','DELA DEPOT','','','0','1','13');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A242','MIDELANA DEPOT','','','1','0','13');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A243','BERUWALA DEPOT','','','0','2','13');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A244','EMBILIPITIYA DEPOT','','','1','0','13');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A245','TIMBOLKETIYA DEPOT','','','0','3','13');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A246','MATUGAMA NEW DEPOT','','','0','4','13');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A247','EGNCY DEPOT HORANA','','','1','0','13');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A248','HADAPANGODA DEPOT','','','1','0','13');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A249','KILINOCHCHI DEPOT','','','0','1','5');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A250','KUMBUKANA  DEPOT','','','0','1','10');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A251','DEHIOWITA DEPOT','','','0','0','13');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A252','PADIYATHALAWA1','','','1','0','1');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A253','BALANGODA DEPOT','','','1','0','13');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A254','INGIRIYA DEPOT','','','1','0','13');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('A255','PELIYAGODA DEPOT','','','0','0','4');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('B001','AMPARA FURNITURE PLANT','','','1','0','1');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('B123','NELUNDENIYA DEPOT 2','','','1','0','7');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('B141','FURNITURE PLANT','','','1','0','8');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('C141','SEASONING AND IMPREG PLANT','','','1','0','8');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('C161','BOOSSA SEAS. AND IMPREG. PLANT','','','1','0','19');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('C201','KEPPITIPOLA IMP PLANT','','','1','0','20');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('D001','FURNITURE PLANT SAW MILL','','','1','0','1');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('D002','FURNITURE PLANT SAW MILL(Temp)','','','1','0','1');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('D021','MEDAWACHCHIYA SAW MILL','','','1','0','2');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('D022','TALAWA SAW MILL','','','1','0','2');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('D023','PADAVIYA SAW MILL','','','1','0','2');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('D041','BORALANDA SAW MILL','','','1','0','3');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('D101','MELSIRIPURA SAW MILL','','','0','0','6');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('D102','NATTANDIYA SAW MILL','','','1','0','6');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('D121','DAMBULLA ARM','','','1','0','7');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('D124','ETHGALA  SAW MILL','','','1','0','7');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('D141','RATHMALANA SAW MILL','','','1','0','8');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('D142','FURNITURE SAW MILL','','','1','0','8');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('D161','BOOSA SAW MILL','','','1','0','19');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('D169','TALALLA SAW MILL','','','1','0','9');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('D181','BUTTALA SAW MILL','','','1','0','10');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('D201','KEPPITIPOLA SAW MILL','','','1','0','20');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('D221','MINNERIYA SAW MILL','','','1','0','12');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('D241','MIDELANA SAW MILL','','','1','0','13');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('D242','DELA SAW MILL','','','1','0','13');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('D243','TIMBOLKETIYA SAW MILL','','','1','0','13');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('E041','BORALANDA MECH WORK SHOP','','','1','0','3');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('E141','MECH. WORK SHOP','','','1','0','18');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F001','AMAPRA ARM','','','1','0','1');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F002','MAHAOYA ARM','','','1','0','1');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F021','WELIOYA LOGGING PROJ','','','1','0','2');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F022','ANURADAPURA ARM','','','1','0','2');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F023','KEBITHIGOLLAWA ARM','','','1','0','2');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F024','KAHATAGASDIGILIYA ARM','','','1','0','2');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F041','OHIYA PROJECT','','','1','0','3');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F042','KINIGAMA NEW PROJECT','','','1','0','3');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F043','MIRISWATTA NURSERY','','','1','0','3');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F044','BORALANDA ARM','','','1','0','3');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F045','BANDARAWELA ARM','','','1','0','3');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F046','HIVALKANDURA DEPOT','','','1','0','3');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F061','MIRIGAMA A.R.M.','','','1','0','4');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F062','COLOMBO A.R.M.','','','1','0','4');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F063','KADAWATHA A.R.M.','','','1','0','4');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F101','PUTTLAM FPU','','','1','0','6');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F102','KURUNEGALA ARM','','','1','0','6');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F103','PUTTALAM ARM','','','1','0','6');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F104','KULIYAPITIYA ARM','','','1','0','6');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F105','NIKAWARATIYA ARM','','','1','0','6');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F121','KANDY ARM','','','1','0','7');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F122','KEGALLE ARM','','','1','0','7');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F123','MATALE ARM','','','1','0','7');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F127','ETHGALA A.R.M.','','','1','0','7');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F161','MIDDENIYA FPU','','','1','0','9');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F162','USWEWA PROJECT','','','1','0','9');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F163','AKURESSA ARM','','','1','0','9');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F164','GALLE ARM','','','1','0','9');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F165','HAMBANTOTA ARM','','','1','0','9');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F181','WELLAWAYA ARM','','','1','0','10');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F182','MONARAGALA ARM','','','1','0','10');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F201','MANTHRI CABLE PROJECT','','','1','0','11');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F202','NUWARAELIYA ARM','','','1','0','11');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F203','CONICAL HILL ARM','','','1','0','11');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F205','NUWARA ELIYA III','','','1','0','11');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F206','NUWARA ELIYA II','','','1','0','11');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F207','NUWARA ELIYA I','','','1','0','11');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F221','MAHAWELI ARM','','','1','0','12');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F222','TRINCO ARM','','','1','0','12');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F223','POLONNARUWA / MINNERIYA ARM','','','1','0','12');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F241','DEHIOWITA FPU','','','1','0','13');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F242','DEHIOWITA ARM','','','1','0','13');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F243','MATUGAMA ARM','','','1','0','13');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F244','RATNAPURA ARM','','','1','0','13');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F245','TIMBOLKETIYA ARM','','','1','0','13');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F246','BALANGODA ARM','','','1','0','13');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F247','KUKULEGANGA PROJECT','','','1','0','13');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F248','TALAWA ARM','','','1','0','2');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F249','MEDAWACHCHIYA ARM','','','1','0','2');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F500','BATTICALOA ARM','','','1','0','1');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('F501','DEDURUOYA  ARM','','','1','0','6');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('G181','KATARAGAMA CIRC. BUNGLOW','','','1','0','10');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('G201','KANDPOLA CIRC BUNGLOW','','','1','0','11');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('H001','AMPARA REGIONAL OFFICE','','','1','0','1');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('H021','ANURADAPURA REG.OFFICE','','','1','0','2');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('H041','BADULLA REG. OFFICE','','','1','0','3');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('H061','COLOMBO REG. OFFICE','','','1','0','4');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('H081','JAFFNA REG. OFFICE','','','1','0','5');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('H101','KURUNEGALA REG OFFICE','','','1','0','6');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('H121','KANDY REG OFFICE','','','1','0','7');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('H141','KALDEMULLA OFFICE','','','1','0','8');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('H161','MATARA REG.OFFICE','','','1','0','9');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('H181','MONARAGALA REG.OFFICE','','','1','0','10');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('H201','NUWARAELIYA REG. OFFICE','','','1','0','11');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('H221','POLONNWRUWA / MINNERIYA RM','','','1','0','12');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('H241','RATNAPURA REG. OFFICE','','','1','0','13');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('I041','SHOW ROOM BANDARAWELA','','','1','0','3');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('I141','SHOW ROOM','','','1','0','8');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('I161','SHOW ROOM UNAWATUNA','','','1','0','9');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('I162','TALALLA SHOW ROOM','','','1','0','9');
insert into `stc_depot`(`depot_id`, `depot_txt`, `deport_tel`, `deport_image`, `priority`, `sortid`, `region_id`) values('I241','RATHNAPURA SHOW ROOM','','','1','0','13');